name: DevOps Assignment CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:

  terraform:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Validate
        run: |
          cd terraform
          terraform validate

      - name: Terraform Format
        run: |
          cd terraform
          terraform fmt -check


  janitor:

    runs-on: ubuntu-latest

    services:

      localstack:

        image: localstack/localstack:3.8.1

        ports:
          - 4566:4566

        env:
          SERVICES: ec2,s3
          DEBUG: 1

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r janitor/requirements.txt

      - name: Wait for LocalStack
        run: |
          sleep 20

      - name: Run Janitor
        run: |
          cd janitor
          python janitor.py --dry-run
